# GitHub Sponsors funding information

# github: [deepskilling]
# patreon: deepskilling
# open_collective: deepskilling
# ko_fi: deepskilling
# custom: ["https://deepskilling.com/support"]

# Uncomment and configure the platforms you want to use for funding

